const Product=[
  {
    "id":1,
    "name":"Kimicchi",
    "image":"/product-images/Kimchi-(asian-food).jpg",
    "price":350,
    "rating":4,
    "category":"asian-food"
  },
  {
    "id":2,
    "name":"Tomyum",
    "image":"/product-images/Tom-Yum-(asian-food).jpg",
    "price":350,
    "rating":4,
    "category":"asian-food"
  },
  {
    "id":3,
    "name":"Shrimp-Scampi-Linguini",
    "image":"/product-images/Shrimp-Scampi-Linguini-(sea-food).jpg",
    "price":200,
    "rating":3,
    "category":"sea-food"
  },
  {
    "id":4,
    "name":"Crab-Cakes",
    "image":"/product-images/Crab-Cakes(sea-food).jpg",
    "price":200,
    "rating":4,
    "category":"sea-food"
  },
  {
    "id":5,
    "name":"Wendys-Chili",
    "image":"/product-images/Wendys-Chili-(fast-food).jpg",
    "price":150,
    "rating":3,
    "category":"fast-food"
  },
  {
    "id":6,
    "name":"King-Chicken-Fries",
    "image":"/product-images/King-Chicken-Fries(fast-food).jpg",
    "price":280,
    "rating":4,
    "category":"fast-food"
  },
  {
    "id":7,
    "name":"Turmeric-Chicken",
    "image":"/product-images/Turmeric-Chicken-(thai-food).jpeg",
    "price":300,
    "rating":4,
    "category":"thai-food"
  },
  {
    "id":8,
    "name":"Massaman-lamb-shoulder",
    "image":"/product-images/massaman-lamb-shoulder(thai-food).jpeg",
    "price":400,
    "rating":4,
    "category":"thai-food"
  },
  {
    "id":9,
    "name":"coconut-chicken",
    "image":"/product-images/golden-cocinut-chicken(thai-food).jpg",
    "price":400,
    "rating":3,
    "category":"thai-food"
  },
  {
    "id":10,
    "name":"Rajma-masala",
    "image":"/product-images/rajma-masala-(veg-food).jpg",
    "price":280,
    "rating":4,
    "category":"veg-food"
  },
  {
    "id":11,
    "name":"Rajma-masala",
    "image":"/product-images/veg-biryani-(veg-food).jpg",
    "price":200,
    "rating":4,
    "category":"veg-food"
  },
  {
    "id":12,
    "name":"Yogurt-Lamb-Curry",
    "image":"/product-images/Yogurt-Lamb-Curry(non-veg-food).jpg",
    "price":200,
    "rating":4,
    "category":"nonveg-food"
  },
  {
    "id":13,
    "name":"Bengali-Fish-Curry",
    "image":"/product-images/Bengali-Fish-Curry(non-veg-food).jpg",
    "price":150,
    "rating":4,
    "category":"nonveg-food"
  },
  {
    "id":14,
    "name":"Saag-Paneer",
    "image":"/product-images/Saag-Paneer(indian-food).jpg",
    "price":200,
    "rating":2,
    "category":"inadian-food"
  },
  {
    "id":15,
    "name":"Matar-Kachori",
    "image":"/product-images/Matar-Kachori(indian-food).jpg",
    "price":200,
    "rating":3,
    "category":"inadian-food"
  },
  {
    "id":17,
    "name":"devils-food-cake",
    "image":"/product-images/devils-food-cake(desert).jpg",
    "price":150,
    "rating":4,
    "category":"desert"
  },
  {
    "id":18,
    "name":"Tiramisu-Layer-Cake",
    "image":"/product-images/Tiramisu-Layer-Cake-(desert).jpg",
    "price":200,
    "rating":4,
    "category":"desert"
  },
  {
    "id":19,
    "name":"Jablonski-Spritz",
    "image":"/product-images/Jablonski-Spritz-(mocktail).jpg",
    "price":200,
    "rating":4,
    "category":"mocktail"
  },
  {
    "id":20,
    "name":"Eastside-Garden",
    "image":"/product-images/Eastside-Garden-(mocktail).jpg",
    "price":200,
    "rating":4,
    "category":"mocktail"
  },
  {
    "id":21,
    "name":"Chicken-Enchiladas",
    "image":"/product-images/Chicken-Enchiladas-(chicken-food).jpg",
    "price":200,
    "rating":4,
    "category":"chicken-food"
  },
  {
    "id":22,
    "name":"Orange-chicken",
    "image":"/product-images/orange-chicken-(chicken-food).jpg",
    "price":200,
    "rating":4,
    "category":"chicken-food"
  },
]
export default Product;